services:
  go_app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./app.env # Load environment variables from the app.env file
    environment:
      - GO_ENV=production
      - PORT=${PORT} # Pass the PORT variable to the container

  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
